### ISSUE TITLE
Konfiguering af nginx på render

### ISSUE THREAD

**Issue by danieljappe** [kea-classrooms/miniproject-kodeklubben#1]
Sidder og kigger på at deploy til render og har formået at få en container op og kører med et image. Problemet opstår nu, at min webpage (https://wishly.onrender.com/), kræver at jeg skal konfigurere nginx eller docker. Jeg er usikker på om at mit docker image(eller container) er tomt og om det skal konfigureres i nginx.conf. Jeg håber du kan hjælpe på min forvirrende situation. 
@lakruzz

**Comment by danieljappe** [comment]
![image](https://user-images.githubusercontent.com/112632294/234218748-3cef43da-4fdb-4ab6-832b-45f1e6ec0cf0.png)
![image](https://user-images.githubusercontent.com/112632294/234218819-fcac467d-1bf2-4d67-9f82-a6fcfed286e9.png)

**Comment by danieljappe** [comment]
https://docs.docker.com/language/java/build-images/
Jeg har fundet den her guide, som jeg vil prøve senere.

**Comment by lakruzz** [comment]
Det var det vi havde workshop om i går i 212 efter frokost.

I det eksempel du har fundet er der ikke styr på MySql - i det tilfælde skal databasen så i en anden container/web app eller den skulle hostes på plantescale.

Jeg har lavet et eksempel som har én `Dockerfile` som kan bygge ét image, med alt hvad I behøver. Det vil sige både MySql og et Jave Runtime Environment.

Eksemplet er baseret på Superhelte projektet - Der er ca [sådan](https://github.com/lakruzz/SuperheltV5/blob/main/Dockerfile) jeres Dockerfile også skal se ud.
